# https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-app
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ (index .Values.ingress.hosts 0).host}}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: k8s-app
            port:
              number: 80